ProyectoFinal/ProyectoFinal/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('pages/',include('page.urls')),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views 

app_name= 'accounts'

urlpatterns = [
    path('signup/',views.signup,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout',views.logout_view,name="logout"),
    path('editarPerfil', views.editarPerfil, name="EditarPerfil"),
    path('crearAvatar', views.agregarAvatar,name="agregarAvatar"),
]

ProyectoFinal/page/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.ArticuloList.as_view(), name='List'),
    path(r'^(?P<pk>\d+)$', views.ArticuloDetalle.as_view(), name='Detail'),
    path('agregar/',views.agregarArticulo,name='agregar'),
    path(r'^editar/(?P<pk>\d+)$', views.ArticuloUpdate.as_view(), name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$', views.ArticuloDelete.as_view(), name='Delete'),
    path('aboutUs/',views.aboutUs, name="AboutUs"),
]

ProyectoFinal/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(default='default.png',blank=True)
     

ProyectoFinal/page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
# Create your models here.

class articulo(models.Model):
    titulo= models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200,default="")
    cuerpo = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(default='default.png',blank=True)
    autor = models.ForeignKey(User,default=None,on_delete=models.CASCADE)

    def __str__(self):
        return f"#{self.id},{self.titulo}"

ProyectoFinal/accounts/forms.py
from dataclasses import field, fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label= 'Contraseña', widget= forms.PasswordInput)
    password2 = forms.CharField(label= 'Repite la contraseña', widget=forms.PasswordInput)


    class Meta:
        model = User                                               #agregamos los campos
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'username': 'Usuario', 'email':'correo'}
        help_texts= {k:"" for k in fields}
        
###
class UserEditForm(UserCreationForm):
    #Aca se define lo que se quiere editar
    email = forms.EmailField(label="Modificar Email")
    password1 = forms.CharField(label='Contrasena', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repetir la contrasena', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class AvatarCreateForm(forms.ModelForm):
    class Meta:
        model= models.Avatar
        fields=['imagen']

ProyectoFinal/page/forms.py
from dataclasses import fields
from socket import fromshare
from django import forms 
from . import models 



class CreateArticulo(forms.ModelForm):
    class Meta:
        model=models.articulo
        fields= ['titulo','descripcion','cuerpo','imagen']

ProyectoFinal/ProyectoFinal/views.py
from django.shortcuts import render
from accounts.models import Avatar


def home(request):
    if request.user.is_authenticated:
        avatares= Avatar.objects.filter(user=request.user)
        if avatares.count() != 0:
            return render(request,'page/home.html',{'url':avatares[0].imagen.url})
    return render(request,'page/home.html')

ProyectoFinal/accounts/views.py
from django.http import request
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from accounts.forms import UserRegisterForm, UserEditForm , AvatarCreateForm 
from accounts.models import Avatar
from django.contrib.auth.decorators import login_required
from .models import Avatar
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.

 



def signup(request):
      
      if request.method == "POST":

            form = UserRegisterForm(request.POST)

            if form.is_valid():
                  username = form.cleaned_data['username']
                 
                  form.save()

                  return render(request, "page/home.html", {"mensaje": "Usuario creado exitosamente"})

      else: 
            form = UserRegisterForm()

      return render(request, "accounts/signup.html", {"form": form})
 
def login_view(request):
   if request.method =='POST':
       form=AuthenticationForm(data=request.POST)
       if form.is_valid():
           user=form.get_user()
           login(request,user)
           return redirect('home')
   else:
       form= AuthenticationForm()
   return render(request,'accounts/login.html',{'formulario':form})
 
def logout_view(request):
   if request.method=='POST':
       logout(request)
       return redirect('home')


###
def editarPerfil(request):
    
    usuario = request.user  #Instancia del login
    if request.method == 'POST':
        
        miFormulario = UserEditForm(request.POST)
        if miFormulario.is_valid():
            
            informacion = miFormulario.cleaned_data
            
            usuario.email = informacion['email']
            usuario.password1 = informacion['password1']
            usuario.password2 = informacion['password2']
            usuario.save()
            
            return render(request, "page/home.html")
    
    else:
        miFormulario = UserEditForm(initial={'email':usuario.email})
        avatares= Avatar.objects.filter(user=request.user)
    return render(request, "accounts/editarPerfil.html", {"miFormulario":miFormulario, "usuario":usuario, "avatar":avatares})


@login_required(login_url="/accounts/login/")
def agregarAvatar(request):
   if request.method =='POST':
       form= AvatarCreateForm(request.POST,request.FILES)
       if form.is_valid() :
           instance = form.save(commit=False)
           instance.user = request.user
           instance.save()
           return render(request,"page/home.html") 
   else:
       form= AvatarCreateForm()
   return render(request,"accounts/agregarAvatar.html",{"formulario":form})

ProyectoFinal/page/views.py
from django.shortcuts import render , redirect
from django.views.generic.detail import DetailView
from .models import articulo
from accounts.models import Avatar
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from . import forms
# Create your views here.
 


def aboutUs(request):
      return render(request, "page/aboutUs.html")


@login_required(login_url="/accounts/login/")
def agregarArticulo(request):
   if request.method =='POST':
       form=forms.CreateArticulo(request.POST,request.FILES)
       if form.is_valid :
           instance = form.save(commit=False)
           instance.autor = request.user
           instance.save()
           return redirect('List') 
   else:
       form= forms.CreateArticulo()
   return render(request,'page/agregar.html',{'formulario':form})


class ArticuloList(ListView):
      model = articulo 
      template_name = "page/articulo_list.html"

class ArticuloDetalle(DetailView):
      model = articulo
      template_name = "page/articulo_detalle.html"


class ArticuloUpdate(UpdateView):
      model = articulo
      success_url = "/pages"
      fields  = ['titulo','descripcion','cuerpo','imagen']


class ArticuloDelete(DeleteView):
      model = articulo
      success_url = "/pages"

ProyectoFinal/accounts/templates/accounts/agregarAvatar.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<br>
<form action="{% url 'accounts:agregarAvatar' %}" method="post" enctype="multipart/form-data">{% csrf_token %} 
        {{formulario}}
    <input type="submit", value="Enviar">
</form>
<br>
<br>
<button><a href="{% url 'home' %}">Volver al inicio</a></button>
{% endblock %}

ProyectoFinal/accounts/templates/accounts/editarPerfil.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<h1>Formulario - Editar perfil de: {{usuario}} </h1>
<br>
<form action="" method="POST">{% csrf_token %}

    <table>
        {{miFormulario.as_table}}
    </table>

    <input type="submit", value="Enviar">

</form>
<br>
<br>
{% if avatar.count != 1 %}
<button><a href="{% url 'accounts:agregarAvatar' %}">Agregar Avatar</a></button>
{% endif %}

<button><a href="{% url 'home' %}">Volver al inicio</a></button>
{% endblock %}

ProyectoFinal/accounts/templates/accounts/login.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<form class="site-form" action="/accounts/login/" method="post">
   {% csrf_token %}
   {{formulario}}
   <input type="submit" value="Login">
  
</form>
{% endblock %}

ProyectoFinal/accounts/templates/accounts/signup.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Registrar</button>
</form>
{% endblock %}

ProyectoFinal/page/templates/page/aboutUs.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<h1> Acerca de nosotros:</h1>
   <h2>Santiago Alfonso y Santiago Ribon son dos estudiantes del curso Python</h2>
   <h2>comisión 27610 de Coder. Trabajaron en conjunto para resolver los desafios y las</h2>
   <h2>entregas finales. Acerca de este blog, consiste en una web donde los usuarios</h2>
   <h2>deben registrarse y pueden agregar y/o ver los articulos que quieran</h2>
   <br>
   <button><a href="{% url 'home' %}">Vuelve al inicio</a></button>
{% endblock %}

ProyectoFinal/page/templates/page/agregar.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
    <h1> Agrega un nuevo post </h1>
    <form class="form-control" action="{% url 'agregar' %}" method="post" enctype="multipart/form-data">
        {{formulario}}
        {% csrf_token %}
        <input type="submit" value="Postear">
    </form>

{% endblock %}

ProyectoFinal/page/templates/page/articulo_confirm_delete.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el curso "{{ object }}"?
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

ProyectoFinal/page/templates/page/articulo_detalle.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
<div class="container px-5">
    <div class="row gx-5 align-items-center">
    <h1>Titulo: <i>{{ articulo.titulo }}</i></h1>
    <p><i>{{articulo.descripcion}}</i></p>
    <p> <i>{{ articulo.cuerpo }}</i></p>
    <p><img src="{{articulo.imagen.url}}" ></p>
    <p> {{articulo.fecha}} </p>
</div>
<button><a href="{% url 'List' %}">Volver</a></button>
</div>
{% endblock %}

ProyectoFinal/page/templates/page/articulo_form.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
    <h1>Nuevo articulo</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="enviar">
    </form>
{% endblock %}

ProyectoFinal/page/templates/page/articulo_list.html
{% extends "page/layout.html" %}
{% load static %}
{% block contenido %}
{% for articulo in object_list %}
<div class="container px-5">
    <div class="row gx-5 align-items-center">
    <li class="list-unstyled">
        <h1> Titulo: {{ articulo.titulo }} </h1>
        <p> {{articulo.descripcion}} </p>
        <img src="{{articulo.imagen.url}}">
        <p> 
            <a href="{% url 'Detail' articulo.id %}">|Ver Mas|</a> 
        {% if user == articulo.autor %}
            <a href="{% url 'Edit' articulo.id %}">Editar|</a> 
            <a href="{% url 'Delete' articulo.id %}">Borrar|</a> 
            {% endif %}
        </p> 
    </li>
</div>
</div>
{% endfor %}
    <a href="{% url 'agregar'  %}" class="page-link">Nuevo</a>
    <br>
    <button><a href="{% url 'home' %}">Vuelve al inicio</a></button>
{% endblock %}

ProyectoFinal/page/templates/page/home.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title> MyBlog </title>
    <link rel="stylesheet" href="{% static 'page/css/styles.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5">
            <a class="navbar-brand fw-bold" href="{% url 'home' %}">Inicio</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'List' %}">Articulos</a></li>
            </ul>
            {% if user.is_authenticated %} 
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <img style="height: 40px; width: 45px; border-radius: 50%;" src="{{url}}">
                <a class="text-muted small mb-4 mb-lg-0" href="{% url 'accounts:EditarPerfil'%}"> Hola {{user.username}}!</a>
            </ul>
           <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">
                    <span class="d-flex align-items-center">
                        <i class="bi-chat-text-fill me-2"></i>
                        <span class="small">Cerrar Sesion</span>
                    </span>
                </button>
            </form>
            {% else %}
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'accounts:login' %}">Iniciar Sesion</a></li>
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'accounts:signup' %}">Registrarse</a></li>
            </ul>
            {% endif %}
            </div>
        </div>
    </nav>

    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <!-- Mashead text and app badges-->
                    <div class="mb-5 mb-lg-0 text-center text-lg-start">
                        <h1 class="display-1 lh-1 mb-3"> MyBlog </h1>
                        <p class="lead fw-normal text-muted mb-5">Aqui puedes encontrar todo tipo de cosas.</p>
                        <div class="d-flex flex-column flex-lg-row align-items-center">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <!-- Masthead device mockup feature-->
                    <div class="masthead-device-mockup">
                        <svg class="circle" viewBox="0 0 100 100" >
                            <defs>
                                <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                    <stop class="gradient-start-color" offset="0%"></stop>
                                    <stop class="gradient-end-color" offset="100%"></stop>
                                </linearGradient>
                            </defs>
                            <circle cx="50" cy="50" r="50"></circle></svg
                        ><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" >
                            <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                            <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect></svg
                        ><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" ><circle cx="50" cy="50" r="50"></circle></svg>

                    </div>
                </div>
            </div>
        </div>
    </header>
    
    
    <!-- Basic features section-->
    <section class="bg-light">
        
            
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
             <h1>Haz clic en articulos para ver los posteos </h1>
                </div>
        
    </section>
    <!-- Call to action section-->
    <section class="cta">
        <div class="cta-content">
            <div class="container px-5">
                <h2 class="text-white display-1 lh-1 mb-4">
                    Conocenos mas.
                    <br />
                </h2>
                <li class="nav-item"><a class="btn btn-outline-light py-3 px-4 rounded-pill" href="{% url 'AboutUs' %}">Sobre Nosotros</a></li>
            </div>
        </div>
    </section>
    <!-- App badge section-->
    <section class="bg-gradient-primary-to-secondary" id="download">
        <div class="container px-5">
            <h2 class="text-center text-white font-alt mb-4"></h2>
        </div>
    </section>
    <footer class="bg-black text-center py-5">
        <div class="container px-5">
            <div class="text-white-50 small">
                <div class="mb-2">&copy; Your Website 2022. All Rights Reserved.</div>
                <a href="#No-hay-pagina-aun">Privacy</a>
                <span class="mx-1">&middot;</span>
                <a href="#No-hay-pagina-aun">Terms</a>
                <span class="mx-1">&middot;</span>
                <a href="#No-hay-pagina-aun">FAQ</a>
            </div>
        </div>
    </footer>
</body>

ProyectoFinal/page/templates/page/layout.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <title> MyBlog </title>
    <link rel="stylesheet" href="{% static 'page/css/styles.css' %}">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5">
            <a class="navbar-brand fw-bold" href="{% url 'home' %}">Inicio</a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'List' %}">Articulos</a></li>
            </ul>
            {% if user.is_authenticated %} 
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <a class="text-muted small mb-4 mb-lg-0" href="{% url 'accounts:EditarPerfil'%}"> Hola {{user.username}}!</a>
            </ul>
           <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">
                    <span class="d-flex align-items-center">
                        <i class="bi-chat-text-fill me-2"></i>
                        <span class="small">Cerrar Sesion</span>
                    </span>
                </button>
            </form>
            {% else %}
            <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'accounts:login' %}">Iniciar Sesion</a></li>
                <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'accounts:signup' %}">Registrarse</a></li>
            </ul>
            {% endif %}
            </div>
        </div>
    </nav>

    <!-- Masthead-->
    <header class="masthead">
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <!-- Mashead text and app badges-->
                    <div class="mb-5 mb-lg-0 text-center text-lg-start">
                        <h1 class="display-1 lh-1 mb-3"> MyBlog </h1>
                        <p class="lead fw-normal text-muted mb-5">Aqui puedes encontrar todo tipo de cosas.</p>
                        <div class="d-flex flex-column flex-lg-row align-items-center">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <!-- Masthead device mockup feature-->
                    <div class="masthead-device-mockup">
                        <svg class="circle" viewBox="0 0 100 100" >
                            <defs>
                                <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                    <stop class="gradient-start-color" offset="0%"></stop>
                                    <stop class="gradient-end-color" offset="100%"></stop>
                                </linearGradient>
                            </defs>
                            <circle cx="50" cy="50" r="50"></circle></svg
                        ><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" >
                            <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                            <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect></svg
                        ><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" ><circle cx="50" cy="50" r="50"></circle></svg>

                    </div>
                </div>
            </div>
        </div>
    </header>
    
    
    <!-- Basic features section-->
    <section class="bg-light">
        
            
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
                    {% block contenido %}
    
                    {% endblock %}
                </div>
        
    </section>
    <!-- Call to action section-->
    <section class="cta">
        <div class="cta-content">
            <div class="container px-5">
                <h2 class="text-white display-1 lh-1 mb-4">
                    Conocenos mas.
                    <br />
                </h2>
                <li class="nav-item"><a class="btn btn-outline-light py-3 px-4 rounded-pill" href="{% url 'AboutUs' %}">Sobre Nosotros</a></li>
            </div>
        </div>
    </section>
    <!-- App badge section-->
    <section class="bg-gradient-primary-to-secondary" id="download">
        <div class="container px-5">
            <h2 class="text-center text-white font-alt mb-4"></h2>
        </div>
    </section>
    <footer class="bg-black text-center py-5">
        <div class="container px-5">
            <div class="text-white-50 small">
                <div class="mb-2">&copy; Your Website 2022. All Rights Reserved.</div>
                <a href="#No-hay-pagina-aun">Privacy</a>
                <span class="mx-1">&middot;</span>
                <a href="#No-hay-pagina-aun">Terms</a>
                <span class="mx-1">&middot;</span>
                <a href="#No-hay-pagina-aun">FAQ</a>
            </div>
        </div>
    </footer>
</body>